//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCenter.ProductManage {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommonResult", Namespace="http://schemas.datacontract.org/2004/07/ShoppingCenterWCF")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ShoppingCenter.ProductManage.ProductsResult))]
    public partial class CommonResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductsResult", Namespace="http://schemas.datacontract.org/2004/07/ShoppingCenterWCF")]
    [System.SerializableAttribute()]
    public partial class ProductsResult : ShoppingCenter.ProductManage.CommonResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ShoppingCenter.ProductManage.Product[] ProductsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ShoppingCenter.ProductManage.Product[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/ShoppingCenterBOL")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ShoppingCenter.ProductManage.Category CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ShoppingCenter.ProductManage.ProductInfo ProductInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ShoppingCenter.ProductManage.Provider ProviderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProviderIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ShoppingCenter.ProductManage.Category Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductDescription {
            get {
                return this.ProductDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductDescriptionField, value) != true)) {
                    this.ProductDescriptionField = value;
                    this.RaisePropertyChanged("ProductDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductImage {
            get {
                return this.ProductImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductImageField, value) != true)) {
                    this.ProductImageField = value;
                    this.RaisePropertyChanged("ProductImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ShoppingCenter.ProductManage.ProductInfo ProductInfo {
            get {
                return this.ProductInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductInfoField, value) != true)) {
                    this.ProductInfoField = value;
                    this.RaisePropertyChanged("ProductInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ShoppingCenter.ProductManage.Provider Provider {
            get {
                return this.ProviderField;
            }
            set {
                if ((object.ReferenceEquals(this.ProviderField, value) != true)) {
                    this.ProviderField = value;
                    this.RaisePropertyChanged("Provider");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProviderId {
            get {
                return this.ProviderIdField;
            }
            set {
                if ((this.ProviderIdField.Equals(value) != true)) {
                    this.ProviderIdField = value;
                    this.RaisePropertyChanged("ProviderId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/ShoppingCenterBOL")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ShoppingCenter.ProductManage.Category[] ChildrenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ShoppingCenter.ProductManage.Category ParentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ShoppingCenter.ProductManage.Product[] ProductsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ShoppingCenter.ProductManage.Category[] Children {
            get {
                return this.ChildrenField;
            }
            set {
                if ((object.ReferenceEquals(this.ChildrenField, value) != true)) {
                    this.ChildrenField = value;
                    this.RaisePropertyChanged("Children");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ShoppingCenter.ProductManage.Category Parent {
            get {
                return this.ParentField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentField, value) != true)) {
                    this.ParentField = value;
                    this.RaisePropertyChanged("Parent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ShoppingCenter.ProductManage.Product[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductInfo", Namespace="http://schemas.datacontract.org/2004/07/ShoppingCenterBOL")]
    [System.SerializableAttribute()]
    public partial class ProductInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BuyTimesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ShoppingCenter.ProductManage.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ViewTimesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BuyTimes {
            get {
                return this.BuyTimesField;
            }
            set {
                if ((this.BuyTimesField.Equals(value) != true)) {
                    this.BuyTimesField = value;
                    this.RaisePropertyChanged("BuyTimes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ShoppingCenter.ProductManage.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ViewTimes {
            get {
                return this.ViewTimesField;
            }
            set {
                if ((this.ViewTimesField.Equals(value) != true)) {
                    this.ViewTimesField = value;
                    this.RaisePropertyChanged("ViewTimes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Provider", Namespace="http://schemas.datacontract.org/2004/07/ShoppingCenterBOL")]
    [System.SerializableAttribute()]
    public partial class Provider : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ShoppingCenter.ProductManage.Product[] ProductsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProviderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProviderNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ShoppingCenter.ProductManage.Product[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProviderId {
            get {
                return this.ProviderIdField;
            }
            set {
                if ((this.ProviderIdField.Equals(value) != true)) {
                    this.ProviderIdField = value;
                    this.RaisePropertyChanged("ProviderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProviderName {
            get {
                return this.ProviderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProviderNameField, value) != true)) {
                    this.ProviderNameField = value;
                    this.RaisePropertyChanged("ProviderName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductManage.IProductManageService")]
    public interface IProductManageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductManageService/GetProductsByCategory", ReplyAction="http://tempuri.org/IProductManageService/GetProductsByCategoryResponse")]
        ShoppingCenter.ProductManage.ProductsResult GetProductsByCategory(int categoryId, int productCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductManageService/GetProductsByCategory", ReplyAction="http://tempuri.org/IProductManageService/GetProductsByCategoryResponse")]
        System.Threading.Tasks.Task<ShoppingCenter.ProductManage.ProductsResult> GetProductsByCategoryAsync(int categoryId, int productCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductManageService/AddProduct", ReplyAction="http://tempuri.org/IProductManageService/AddProductResponse")]
        ShoppingCenter.ProductManage.CommonResult AddProduct(ShoppingCenter.ProductManage.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductManageService/AddProduct", ReplyAction="http://tempuri.org/IProductManageService/AddProductResponse")]
        System.Threading.Tasks.Task<ShoppingCenter.ProductManage.CommonResult> AddProductAsync(ShoppingCenter.ProductManage.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductManageService/RemoveProduct", ReplyAction="http://tempuri.org/IProductManageService/RemoveProductResponse")]
        ShoppingCenter.ProductManage.CommonResult RemoveProduct(ShoppingCenter.ProductManage.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductManageService/RemoveProduct", ReplyAction="http://tempuri.org/IProductManageService/RemoveProductResponse")]
        System.Threading.Tasks.Task<ShoppingCenter.ProductManage.CommonResult> RemoveProductAsync(ShoppingCenter.ProductManage.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductManageService/EditProduct", ReplyAction="http://tempuri.org/IProductManageService/EditProductResponse")]
        ShoppingCenter.ProductManage.CommonResult EditProduct(ShoppingCenter.ProductManage.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductManageService/EditProduct", ReplyAction="http://tempuri.org/IProductManageService/EditProductResponse")]
        System.Threading.Tasks.Task<ShoppingCenter.ProductManage.CommonResult> EditProductAsync(ShoppingCenter.ProductManage.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductManageService/AddCategory", ReplyAction="http://tempuri.org/IProductManageService/AddCategoryResponse")]
        ShoppingCenter.ProductManage.CommonResult AddCategory(ShoppingCenter.ProductManage.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductManageService/AddCategory", ReplyAction="http://tempuri.org/IProductManageService/AddCategoryResponse")]
        System.Threading.Tasks.Task<ShoppingCenter.ProductManage.CommonResult> AddCategoryAsync(ShoppingCenter.ProductManage.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductManageService/RemoveCategory", ReplyAction="http://tempuri.org/IProductManageService/RemoveCategoryResponse")]
        ShoppingCenter.ProductManage.CommonResult RemoveCategory(ShoppingCenter.ProductManage.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductManageService/RemoveCategory", ReplyAction="http://tempuri.org/IProductManageService/RemoveCategoryResponse")]
        System.Threading.Tasks.Task<ShoppingCenter.ProductManage.CommonResult> RemoveCategoryAsync(ShoppingCenter.ProductManage.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductManageService/EditCategory", ReplyAction="http://tempuri.org/IProductManageService/EditCategoryResponse")]
        ShoppingCenter.ProductManage.CommonResult EditCategory(ShoppingCenter.ProductManage.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductManageService/EditCategory", ReplyAction="http://tempuri.org/IProductManageService/EditCategoryResponse")]
        System.Threading.Tasks.Task<ShoppingCenter.ProductManage.CommonResult> EditCategoryAsync(ShoppingCenter.ProductManage.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductManageService/GetAllCategory", ReplyAction="http://tempuri.org/IProductManageService/GetAllCategoryResponse")]
        ShoppingCenter.ProductManage.Category[] GetAllCategory();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductManageService/GetAllCategory", ReplyAction="http://tempuri.org/IProductManageService/GetAllCategoryResponse")]
        System.Threading.Tasks.Task<ShoppingCenter.ProductManage.Category[]> GetAllCategoryAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductManageServiceChannel : ShoppingCenter.ProductManage.IProductManageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductManageServiceClient : System.ServiceModel.ClientBase<ShoppingCenter.ProductManage.IProductManageService>, ShoppingCenter.ProductManage.IProductManageService {
        
        public ProductManageServiceClient() {
        }
        
        public ProductManageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductManageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductManageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductManageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ShoppingCenter.ProductManage.ProductsResult GetProductsByCategory(int categoryId, int productCount) {
            return base.Channel.GetProductsByCategory(categoryId, productCount);
        }
        
        public System.Threading.Tasks.Task<ShoppingCenter.ProductManage.ProductsResult> GetProductsByCategoryAsync(int categoryId, int productCount) {
            return base.Channel.GetProductsByCategoryAsync(categoryId, productCount);
        }
        
        public ShoppingCenter.ProductManage.CommonResult AddProduct(ShoppingCenter.ProductManage.Product product) {
            return base.Channel.AddProduct(product);
        }
        
        public System.Threading.Tasks.Task<ShoppingCenter.ProductManage.CommonResult> AddProductAsync(ShoppingCenter.ProductManage.Product product) {
            return base.Channel.AddProductAsync(product);
        }
        
        public ShoppingCenter.ProductManage.CommonResult RemoveProduct(ShoppingCenter.ProductManage.Product product) {
            return base.Channel.RemoveProduct(product);
        }
        
        public System.Threading.Tasks.Task<ShoppingCenter.ProductManage.CommonResult> RemoveProductAsync(ShoppingCenter.ProductManage.Product product) {
            return base.Channel.RemoveProductAsync(product);
        }
        
        public ShoppingCenter.ProductManage.CommonResult EditProduct(ShoppingCenter.ProductManage.Product product) {
            return base.Channel.EditProduct(product);
        }
        
        public System.Threading.Tasks.Task<ShoppingCenter.ProductManage.CommonResult> EditProductAsync(ShoppingCenter.ProductManage.Product product) {
            return base.Channel.EditProductAsync(product);
        }
        
        public ShoppingCenter.ProductManage.CommonResult AddCategory(ShoppingCenter.ProductManage.Category category) {
            return base.Channel.AddCategory(category);
        }
        
        public System.Threading.Tasks.Task<ShoppingCenter.ProductManage.CommonResult> AddCategoryAsync(ShoppingCenter.ProductManage.Category category) {
            return base.Channel.AddCategoryAsync(category);
        }
        
        public ShoppingCenter.ProductManage.CommonResult RemoveCategory(ShoppingCenter.ProductManage.Category category) {
            return base.Channel.RemoveCategory(category);
        }
        
        public System.Threading.Tasks.Task<ShoppingCenter.ProductManage.CommonResult> RemoveCategoryAsync(ShoppingCenter.ProductManage.Category category) {
            return base.Channel.RemoveCategoryAsync(category);
        }
        
        public ShoppingCenter.ProductManage.CommonResult EditCategory(ShoppingCenter.ProductManage.Category category) {
            return base.Channel.EditCategory(category);
        }
        
        public System.Threading.Tasks.Task<ShoppingCenter.ProductManage.CommonResult> EditCategoryAsync(ShoppingCenter.ProductManage.Category category) {
            return base.Channel.EditCategoryAsync(category);
        }
        
        public ShoppingCenter.ProductManage.Category[] GetAllCategory() {
            return base.Channel.GetAllCategory();
        }
        
        public System.Threading.Tasks.Task<ShoppingCenter.ProductManage.Category[]> GetAllCategoryAsync() {
            return base.Channel.GetAllCategoryAsync();
        }
    }
}
